#update properties
#Mon Jul 01 15:26:23 CEST 2024
dir.current=C\:\\java\\encrypter-test\\test-updt
dir.default=C\:\\java\\encrypter-test\\test-updt\\empty
savein.currentdir=true
savein.defaultdir=false
